/*
 * STUB implementation of Wire's AVS (Audio Video Signaling) framework.
 *
 * Kalium 0.0.7's calling module links `-framework avs`, but the real AVS binary is Wire's
 * proprietary artifact and is NOT published to Maven. This stub defines just the symbols the
 * Kotlin/Native cinterop references, so the app LINKS and RUNS for testing everything except
 * calling. Calling is disabled at runtime (KaliumConfigs.enableCalling = false); none of these
 * are meant to be invoked. Replace this stub with Wire's real avs.xcframework to enable calling.
 *
 * Auto-generated by build-avs-stub.sh from the linker's undefined-symbol report. Do not edit by hand.
 */
#import <Foundation/Foundation.h>

@interface AVSFlowManager : NSObject @end
@implementation AVSFlowManager @end
@interface AVSMediaManager : NSObject @end
@implementation AVSMediaManager @end

// wcall_* C functions (no-ops; C symbols carry no argument info, so a nullary stub satisfies the linker)
int wcall_answer(void) { return 0; }
int wcall_config_update(void) { return 0; }
int wcall_create(void) { return 0; }
int wcall_end(void) { return 0; }
int wcall_network_changed(void) { return 0; }
int wcall_process_notifications(void) { return 0; }
int wcall_recv_msg(void) { return 0; }
int wcall_reject(void) { return 0; }
int wcall_request_video_streams(void) { return 0; }
int wcall_resp(void) { return 0; }
int wcall_run(void) { return 0; }
int wcall_set_active_speaker_handler(void) { return 0; }
int wcall_set_background(void) { return 0; }
int wcall_set_clients_for_conv(void) { return 0; }
int wcall_set_epoch_info(void) { return 0; }
int wcall_set_group_changed_handler(void) { return 0; }
int wcall_set_log_handler(void) { return 0; }
int wcall_set_mute(void) { return 0; }
int wcall_set_mute_handler(void) { return 0; }
int wcall_set_network_quality_handler(void) { return 0; }
int wcall_set_participant_changed_handler(void) { return 0; }
int wcall_set_req_clients_handler(void) { return 0; }
int wcall_set_req_new_epoch_handler(void) { return 0; }
int wcall_set_video_send_state(void) { return 0; }
int wcall_setup(void) { return 0; }
int wcall_sft_resp(void) { return 0; }
int wcall_start(void) { return 0; }
